### ISSUE TITLE
[BUG] Unexpected behavior in AZ-AAD-AI-1.1

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#105]
**Describe the bug**
Test fails, shouldn't

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Additional context**
Review `iCreateAnAzureIdentityBindingCalledInANondefaultNamespace` to find intended and actual behavior

**Comment by eddie-knight** [comment]
This test may be "passing" but needs refinement in passing the state

**Comment by simonwoolhouse** [comment]
@iantivey
The corresponding iam feature scenario ‘Prevent cross namespace Azure Identity Bindings‘ has the following steps:
1.	Given a Kubernetes cluster exists which we can deploy into
2.	And the default namespace has an AzureIdentity
3.	When I create an AzureIdentityBinding called "probr-aib" in a non-default namespace
4.	And I deploy a pod assigned with the "probr-aib" AzureIdentityBinding into the same namespace as the "probr-aib" AzureIdentityBinding 
5.	Then the pod is deployed successfully
6.	But an attempt to obtain an access token from that pod should fail

Probr currently fails on step 3

It appears that the code mapped to Step 3 is not actually doing what the step requires, but instead is doing a very similar test to Step 2

Looking at the code for Step 2 it:
-	Connects to the Kubernetes cluster to get resources associated with the group “AzureIdentity”
-	Checks whether any of the resources have a namespace = “default” and if so returns Success, otherwise Fail
This returns Success

Looking at the code for Step 3 it doesn’t attempt to create a AzureIdentityBinding but instead carries out a similar check to Step 2, as follows:
-	Connects to the Kubernetes cluster to get resources associated with the group “AzureIdentityBinding”
-	Checks whether any of the resources have a namespace != “default” and if so returns Success, otherwise Fail
This returns Fail because the only resource returned has a namepace = “default”

So, do we need to rewrite the code to attempt to create an AzureIdentityBinding?

**Comment by simonwoolhouse** [comment]
Assuming we need to create an AzureIdentityBinding resource, this will be useful - https://github.com/Azure/aad-pod-identity/tree/master/examples/rest-api

**Comment by simonwoolhouse** [comment]
Following advice from Paul, I was able to manually create the required AzureIdentityBinding in our test cluster via kubectl, using the yaml below:

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: probr-aib
  namespace: probr-rbac-test-ns
spec:
  azureIdentity: probr-probe
  selector:  aadpodidbinding

The scenario now runs successfully - pod gets created with the AzureIdentity but can't obtain an access token.
Next step is to create the AzureIdentityBinding in the non-default namespace programmatically

**Comment by simonwoolhouse** [comment]
Dave had implemented a CreateAIB method aimed at creating an 'AzureIdentityBinding' resource within Probr from the yaml file which works via kubectl.
However, the yaml is not successfully decoded using the default codec. The decoder doesn't return an error, but the returned object is empty.

**Comment by paulm-jones** [comment]
#81

**Comment by paulm-jones** [comment]
> Dave had implemented a CreateAIB method aimed at creating an 'AzureIdentityBinding' resource within Probr from the yaml file which works via kubectl.

Wow that's a tough bit of code to read! I hope we can simplify that, will have a look.

**Comment by simonwoolhouse** [comment]
Can successfully create a local AIB object programmatically with attributes defined in the working yaml as follows:
	aib := aibv1.AzureIdentityBinding{
		TypeMeta: metav1.TypeMeta{
			Kind: "AzureIdentityBinding",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "probr-aib",
			Namespace: "probr-rbac-test-ns",
		},
		Spec: aibv1.AzureIdentityBindingSpec{
			AzureIdentity: "probr-probe",
			Selector:      "aadpodidbinding",
		},
	}
with import:
aibv1 "github.com/Azure/aad-pod-identity/pkg/apis/aadpodidentity"

But not yet able to successfully create the resource on the cluster via the REST api.
Passing aib into c.CoreV1().RESTClient().Post().Body does not work
